build:
	docker build -f backend/Dockerfile-lambda --no-cache  --platform linux/x86_64 -t meal-planner backend/
	docker tag meal-planner:latest 879100528238.dkr.ecr.us-east-1.amazonaws.com/meal-planner:latest
test:
	curl -XPOST "http://localhost:9000/2015-03-31/functions/function/invocations" -d '{}'

test-get:
	curl -XPOST "http://localhost:9000/2015-03-31/functions/function/invocations" \
		-H "Content-Type: application/json" \
		-d '{"resource": "/api/", "path": "/api/", "httpMethod": "GET", "headers": {"Content-Type": "application/json"}, "multiValueHeaders": {}, "queryStringParameters": null, "multiValueQueryStringParameters": null, "pathParameters": null, "stageVariables": null, "requestContext": {"resourcePath": "/api/", "httpMethod": "GET", "path": "/api/", "accountId": "123456789012", "stage": "test", "requestId": "test-invoke-request", "identity": {"sourceIp": "127.0.0.1"}, "domainName": "test.execute-api.us-east-1.amazonaws.com", "apiId": "test123"}, "body": null, "isBase64Encoded": false}' \
		| jq '.'

test-get-v2:
	curl -XPOST "http://localhost:9000/2015-03-31/functions/function/invocations" \
		-H "Content-Type: application/json" \
		-d '{"version": "2.0", "routeKey": "GET /api/", "rawPath": "/api/", "rawQueryString": "", "headers": {"content-type": "application/json"}, "requestContext": {"accountId": "123456789012", "apiId": "test123", "domainName": "test.execute-api.us-east-1.amazonaws.com", "domainPrefix": "test123", "http": {"method": "GET", "path": "/api/", "protocol": "HTTP/1.1", "sourceIp": "127.0.0.1", "userAgent": "curl"}, "requestId": "test-invoke-request", "routeKey": "GET /api/", "stage": "$default", "time": "06/Jan/2026:00:00:00 +0000", "timeEpoch": 1736121600000}, "isBase64Encoded": false}' \
		| jq '.'

test-get-function-url:
	curl -XPOST "http://localhost:9000/2015-03-31/functions/function/invocations" \
		-H "Content-Type: application/json" \
		-d '{"version": "2.0", "routeKey": "$default", "rawPath": "/api/", "rawQueryString": "", "headers": {"accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7", "accept-encoding": "gzip, deflate, br, zstd", "accept-language": "en-CA,en;q=0.9", "cache-control": "max-age=0", "host": "qbonyismza6nyyp4mqxo5424ji0jhima.lambda-url.us-east-1.on.aws", "sec-fetch-dest": "document", "sec-fetch-mode": "navigate", "sec-fetch-site": "none", "sec-fetch-user": "?1", "upgrade-insecure-requests": "1", "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36", "sec-ch-ua": "\"Google Chrome\";v=\"143\", \"Chromium\";v=\"143\", \"Not A(Brand)\";v=\"24\"", "sec-ch-ua-mobile": "?0", "sec-ch-ua-platform": "\"macOS\""}, "requestContext": {"accountId": "anonymous", "apiId": "qbonyismza6nyyp4mqxo5424ji0jhima", "domainName": "qbonyismza6nyyp4mqxo5424ji0jhima.lambda-url.us-east-1.on.aws", "domainPrefix": "qbonyismza6nyyp4mqxo5424ji0jhima", "http": {"method": "GET", "path": "/api/", "protocol": "HTTP/1.1", "sourceIp": "127.0.0.1", "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36"}, "requestId": "test-invoke-request", "routeKey": "$default", "stage": "$default", "time": "06/Jan/2026:00:00:00 +0000", "timeEpoch": 1736121600000}, "isBase64Encoded": false}' \
		| jq '.'

test-hello:
	curl -XPOST "http://localhost:9000/2015-03-31/functions/function/invocations" \
		-H "Content-Type: application/json" \
		-d '{"version": "2.0", "routeKey": "$default", "rawPath": "/hello/", "rawQueryString": "", "headers": {"accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7", "accept-encoding": "gzip, deflate, br, zstd", "accept-language": "en-CA,en;q=0.9", "cache-control": "max-age=0", "host": "qbonyismza6nyyp4mqxo5424ji0jhima.lambda-url.us-east-1.on.aws", "sec-fetch-dest": "document", "sec-fetch-mode": "navigate", "sec-fetch-site": "none", "sec-fetch-user": "?1", "upgrade-insecure-requests": "1", "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36", "sec-ch-ua": "\"Google Chrome\";v=\"143\", \"Chromium\";v=\"143\", \"Not A(Brand)\";v=\"24\"", "sec-ch-ua-mobile": "?0", "sec-ch-ua-platform": "\"macOS\""}, "requestContext": {"accountId": "anonymous", "apiId": "qbonyismza6nyyp4mqxo5424ji0jhima", "domainName": "qbonyismza6nyyp4mqxo5424ji0jhima.lambda-url.us-east-1.on.aws", "domainPrefix": "qbonyismza6nyyp4mqxo5424ji0jhima", "http": {"method": "GET", "path": "/hello/", "protocol": "HTTP/1.1", "sourceIp": "127.0.0.1", "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36"}, "requestId": "test-invoke-request", "routeKey": "$default", "stage": "$default", "time": "06/Jan/2026:00:00:00 +0000", "timeEpoch": 1736121600000}, "isBase64Encoded": false}' \
		| jq '.'

test-hello-without-slash:
	curl -XPOST "http://localhost:9000/2015-03-31/functions/function/invocations" \
		-H "Content-Type: application/json" \
		-d '{"version": "2.0", "routeKey": "$default", "rawPath": "/hello", "rawQueryString": "", "headers": {"accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7", "accept-encoding": "gzip, deflate, br, zstd", "accept-language": "en-CA,en;q=0.9", "cache-control": "max-age=0", "host": "qbonyismza6nyyp4mqxo5424ji0jhima.lambda-url.us-east-1.on.aws", "sec-fetch-dest": "document", "sec-fetch-mode": "navigate", "sec-fetch-site": "none", "sec-fetch-user": "?1", "upgrade-insecure-requests": "1", "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36", "sec-ch-ua": "\"Google Chrome\";v=\"143\", \"Chromium\";v=\"143\", \"Not A(Brand)\";v=\"24\"", "sec-ch-ua-mobile": "?0", "sec-ch-ua-platform": "\"macOS\""}, "requestContext": {"accountId": "anonymous", "apiId": "qbonyismza6nyyp4mqxo5424ji0jhima", "domainName": "qbonyismza6nyyp4mqxo5424ji0jhima.lambda-url.us-east-1.on.aws", "domainPrefix": "qbonyismza6nyyp4mqxo5424ji0jhima", "http": {"method": "GET", "path": "/hello", "protocol": "HTTP/1.1", "sourceIp": "127.0.0.1", "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36"}, "requestId": "test-invoke-request", "routeKey": "$default", "stage": "$default", "time": "06/Jan/2026:00:00:00 +0000", "timeEpoch": 1736121600000}, "isBase64Encoded": false}' \
		| jq '.'

test-api-without-slash:
	curl -XPOST "http://localhost:9000/2015-03-31/functions/function/invocations" \
		-H "Content-Type: application/json" \
		-d '{"version": "2.0", "routeKey": "$default", "rawPath": "/api", "rawQueryString": "", "headers": {"accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7", "accept-encoding": "gzip, deflate, br, zstd", "accept-language": "en-CA,en;q=0.9", "cache-control": "max-age=0", "host": "qbonyismza6nyyp4mqxo5424ji0jhima.lambda-url.us-east-1.on.aws", "sec-fetch-dest": "document", "sec-fetch-mode": "navigate", "sec-fetch-site": "none", "sec-fetch-user": "?1", "upgrade-insecure-requests": "1", "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36", "sec-ch-ua": "\"Google Chrome\";v=\"143\", \"Chromium\";v=\"143\", \"Not A(Brand)\";v=\"24\"", "sec-ch-ua-mobile": "?0", "sec-ch-ua-platform": "\"macOS\""}, "requestContext": {"accountId": "anonymous", "apiId": "qbonyismza6nyyp4mqxo5424ji0jhima", "domainName": "qbonyismza6nyyp4mqxo5424ji0jhima.lambda-url.us-east-1.on.aws", "domainPrefix": "qbonyismza6nyyp4mqxo5424ji0jhima", "http": {"method": "GET", "path": "/api", "protocol": "HTTP/1.1", "sourceIp": "127.0.0.1", "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36"}, "requestId": "test-invoke-request", "routeKey": "$default", "stage": "$default", "time": "06/Jan/2026:00:00:00 +0000", "timeEpoch": 1736121600000}, "isBase64Encoded": false}' \
		| jq '.'

test-meal-plan-without-slash:
	curl -XPOST "http://localhost:9000/2015-03-31/functions/function/invocations" \
		-H "Content-Type: application/json" \
		-d '{"version": "2.0", "routeKey": "$default", "rawPath": "/api/meal-plans", "rawQueryString": "", "headers": {"accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7", "accept-encoding": "gzip, deflate, br, zstd", "accept-language": "en-CA,en;q=0.9", "cache-control": "max-age=0", "host": "qbonyismza6nyyp4mqxo5424ji0jhima.lambda-url.us-east-1.on.aws", "sec-fetch-dest": "document", "sec-fetch-mode": "navigate", "sec-fetch-site": "none", "sec-fetch-user": "?1", "upgrade-insecure-requests": "1", "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36", "sec-ch-ua": "\"Google Chrome\";v=\"143\", \"Chromium\";v=\"143\", \"Not A(Brand)\";v=\"24\"", "sec-ch-ua-mobile": "?0", "sec-ch-ua-platform": "\"macOS\""}, "requestContext": {"accountId": "anonymous", "apiId": "qbonyismza6nyyp4mqxo5424ji0jhima", "domainName": "qbonyismza6nyyp4mqxo5424ji0jhima.lambda-url.us-east-1.on.aws", "domainPrefix": "qbonyismza6nyyp4mqxo5424ji0jhima", "http": {"method": "GET", "path": "/api/meal-plans", "protocol": "HTTP/1.1", "sourceIp": "127.0.0.1", "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36"}, "requestId": "test-invoke-request", "routeKey": "$default", "stage": "$default", "time": "06/Jan/2026:00:00:00 +0000", "timeEpoch": 1736121600000}, "isBase64Encoded": false}' \
		| jq '.'

