# Generated by Django 4.2.24 on 2026-05-18 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_add_meal_settings_day_toggles'),
        ('meals', '0003_dailymeal_date_day_of_week'),
    ]

    operations = [
    ]
